# Generated by Django 4.2 on 2023-05-14 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chairmans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middlename', models.CharField(max_length=50, verbose_name='Отчество')),
                ('name_eng', models.CharField(default='', max_length=100, verbose_name='Имя на английском')),
                ('lastname_eng', models.CharField(default='', max_length=100, verbose_name='Фамилия на английском')),
                ('middlename_eng', models.CharField(default='', max_length=100, verbose_name='Отчество на английском')),
                ('job', models.CharField(default='', max_length=100, verbose_name='Место работы')),
                ('scientific_degree', models.CharField(default='', max_length=100, verbose_name='Степень')),
                ('number', models.CharField(default='', max_length=12, verbose_name='Номер телефона')),
                ('email', models.CharField(default='', max_length=50, verbose_name='Почта')),
                ('initials', models.CharField(default='', max_length=100, verbose_name='Инициалы')),
            ],
            options={
                'verbose_name': 'Chairman',
            },
        ),
        migrations.CreateModel(
            name='Commissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middlename', models.CharField(max_length=50, verbose_name='Отчество')),
                ('name_eng', models.CharField(max_length=100, verbose_name='Имя на английском')),
                ('lastname_eng', models.CharField(max_length=100, verbose_name='Фамилия на английском')),
                ('middlename_eng', models.CharField(max_length=100, verbose_name='Отчество на английском')),
                ('job', models.CharField(max_length=100, verbose_name='Место работы')),
                ('scientific_degree', models.CharField(max_length=100, verbose_name='Степень')),
                ('number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('initials', models.CharField(max_length=100, verbose_name='Инициалы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission',
            },
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middlename', models.CharField(max_length=50, verbose_name='Отчество')),
                ('name_eng', models.CharField(default='', max_length=100, verbose_name='Имя на английском')),
                ('lastname_eng', models.CharField(default='', max_length=100, verbose_name='Фамилия на английском')),
                ('middlename_eng', models.CharField(default='', max_length=100, verbose_name='Отчество на английском')),
                ('job', models.CharField(default='', max_length=100, verbose_name='Место работы')),
                ('number', models.CharField(default='', max_length=12, verbose_name='Номер телефона')),
                ('email', models.CharField(default='', max_length=50, verbose_name='Почта')),
                ('initials', models.CharField(default='', max_length=100, verbose_name='Инициалы')),
            ],
            options={
                'verbose_name': 'Secretarie',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middlename', models.CharField(max_length=50, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='День рождения')),
                ('diploma_title', models.CharField(max_length=100, verbose_name='Тема дипломного проекта')),
                ('iin', models.CharField(default='', max_length=100, verbose_name='ИИН')),
                ('name_eng', models.CharField(default='', max_length=100, verbose_name='Имя на английском')),
                ('lastname_eng', models.CharField(default='', max_length=100, verbose_name='Фамилия на английском')),
                ('middlename_eng', models.CharField(default='', max_length=100, verbose_name='Отчество на английском')),
                ('id_card', models.CharField(default='', max_length=100, verbose_name='№ удостоверения личности/паспорта')),
                ('speciality', models.CharField(default='', max_length=100, verbose_name='Специальность')),
                ('diploma', models.FileField(default='', upload_to='uploads/', verbose_name='Диплом')),
                ('prez_diploma', models.FileField(default='', upload_to='uploads/', verbose_name='Презентация')),
                ('recen_diploma', models.FileField(default='', upload_to='uploads/', verbose_name='Рецензия')),
                ('feedback_diploma', models.FileField(default='', upload_to='uploads/', verbose_name='Отзыв руководителя')),
                ('antiplagiat', models.FileField(default='', upload_to='uploads/', verbose_name='Антиплагиат')),
                ('time', models.TimeField(auto_now_add=True, null=True, verbose_name='Время сдачи диплома')),
                ('endtime', models.TimeField(auto_now_add=True, null=True, verbose_name='Время окончание сдачи диплома')),
                ('date', models.DateField(blank=True, default='2000-01-01', null=True, verbose_name='Дата сдачи диплома')),
                ('advisor', models.CharField(default='', max_length=100, verbose_name='Руководитель')),
                ('advisor_scientific_degree', models.CharField(default='', max_length=100, verbose_name='Степень руководителя')),
                ('advisor_job', models.CharField(default='', max_length=100, verbose_name='Место работы руководителя')),
            ],
            options={
                'verbose_name': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard2.commissions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard2.students')),
            ],
        ),
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard2.students')),
            ],
        ),
    ]
