# Generated by Django 4.2 on 2023-05-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard2', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='question',
            field=models.CharField(default='', max_length=100),
        ),
    ]
