# Generated by Django 4.2 on 2023-05-16 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard2', '0003_grade_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='commission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard2.userprofile'),
        ),
    ]
