# Generated by Django 4.2 on 2023-05-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard2', '0005_alter_grade_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
    ]
