# Generated by Django 4.2 on 2023-05-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard2', '0006_grade_is_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='defense',
            name='coment',
            field=models.CharField(default=''),
        ),
    ]
