# Generated by Django 4.2 on 2023-05-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard2', '0008_alter_defense_end_time_alter_defense_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='defense',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
    ]
