# Generated by Django 4.2 on 2023-05-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard2', '0009_defense_is_filled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='students',
            name='time',
        ),
        migrations.AddField(
            model_name='defense',
            name='comment_2',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defense',
            name='comment_3',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defense',
            name='page_number',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defense',
            name='picture_number',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defense',
            name='score',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defense',
            name='text_area',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defense',
            name='text_input',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defense',
            name='text_input_1',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='defense',
            name='coment',
            field=models.CharField(default='', max_length=500),
        ),
    ]
