# Generated by Django 4.2 on 2023-05-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard2', '0010_remove_students_endtime_remove_students_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='advisor_initials',
            field=models.CharField(default='', max_length=100, verbose_name='Руководитель инициалы'),
        ),
    ]
