# Generated by Django 4.2 on 2023-05-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard2', '0011_students_advisor_initials'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='gpa',
            field=models.CharField(default='', max_length=10, verbose_name='GPA'),
        ),
    ]
