# Generated by Django 4.2 on 2023-05-25 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard2', '0013_chairmans_user_secretary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chairman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bboard2.chairmans'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bboard2.commissions'),
        ),
    ]
