# Generated by Django 4.2 on 2023-05-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard2', '0015_grade_chairman_alter_grade_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chairmans',
            name='lastname_eng',
        ),
        migrations.RemoveField(
            model_name='chairmans',
            name='middlename_eng',
        ),
        migrations.RemoveField(
            model_name='chairmans',
            name='name_eng',
        ),
        migrations.RemoveField(
            model_name='commissions',
            name='lastname_eng',
        ),
        migrations.RemoveField(
            model_name='commissions',
            name='middlename_eng',
        ),
        migrations.RemoveField(
            model_name='commissions',
            name='name_eng',
        ),
        migrations.RemoveField(
            model_name='secretary',
            name='lastname_eng',
        ),
        migrations.RemoveField(
            model_name='secretary',
            name='middlename_eng',
        ),
        migrations.RemoveField(
            model_name='secretary',
            name='name_eng',
        ),
        migrations.RemoveField(
            model_name='students',
            name='lastname_eng',
        ),
        migrations.RemoveField(
            model_name='students',
            name='middlename_eng',
        ),
        migrations.RemoveField(
            model_name='students',
            name='name_eng',
        ),
        migrations.AlterField(
            model_name='defense',
            name='comment_2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='defense',
            name='comment_3',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='defense',
            name='page_number',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='defense',
            name='picture_number',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='defense',
            name='score',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='defense',
            name='text_area',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='defense',
            name='text_input',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='defense',
            name='text_input_1',
            field=models.CharField(default='', max_length=500),
        ),
    ]
