# Generated by Django 4.2 on 2023-05-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard2', '0016_remove_chairmans_lastname_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissions',
            name='scientific_degree',
            field=models.CharField(max_length=500, verbose_name='Степень'),
        ),
    ]
