# Generated by Django 4.2 on 2023-06-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard2', '0017_alter_commissions_scientific_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairmans',
            name='middlename',
            field=models.CharField(max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='commissions',
            name='middlename',
            field=models.CharField(max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='middlename',
            field=models.CharField(max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='students',
            name='middlename',
            field=models.CharField(max_length=50, null=True, verbose_name='Отчество'),
        ),
    ]
