# Generated by Django 4.2 on 2023-06-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard2', '0018_alter_chairmans_middlename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairmans',
            name='middlename',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='middlename',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='students',
            name='middlename',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
    ]
